Minor cleanup

diff --git a/bin/gmsg b/bin/gmsg
--- a/bin/gmsg
+++ b/bin/gmsg
@@ -10,10 +10,10 @@
 
 set -u
 
-PATH_THIS="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)/"$(basename -- "${BASH_SOURCE[0]}")""
-DIR_THIS="$(dirname -- "${PATH_THIS}")"
-BASE_THIS="$(basename -- "${PATH_THIS}")"
-[ -f "${PATH_THIS}" ] && [ -d "${DIR_THIS}" ] && [ -f "${DIR_THIS}/${BASE_THIS}" ] || ! echo >&2 "ERROR: could not generate paths" || exit 1
+path_this="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)/$(basename -- "${BASH_SOURCE[0]}")"
+dir_this="$(dirname -- "${path_this}")"
+base_this="$(basename -- "${path_this}")"
+[ -f "${path_this}" ] && [ -d "${dir_this}" ] && [ -f "${dir_this}/${base_this}" ] || ! echo >&2 "ERROR: could not generate paths" || exit 1
 
 __parse_args() {
     while (("${#}")); do
@@ -24,12 +24,12 @@ __parse_args() {
             ;;
         --dir | -d) # select the git directory to execute this script in
             dir_root="${2}"
-            [ -d "${dir_root}" ] || ! echo >&2 "ERROR: ${BASE_THIS}: param '${2}' for '${1}' is not a valid dir"
+            [ -d "${dir_root}" ] || ! echo >&2 "ERROR: ${base_this}: param '${2}' for '${1}' is not a valid dir"
             shift
             ;;
         *)
             git_ref="${1}"
-            echo >&2 "INFO: ${BASE_THIS}: using '${1}' as '--commit' arg"
+            echo >&2 "INFO: ${base_this}: using '${1}' as '--commit' arg"
             ;;
         esac
         shift
@@ -43,12 +43,12 @@ _gmsg() {
     #### parse script args and overwrite vars
     __parse_args "${@}" || return "${?}"
     #### check git refs
-    git cat-file -e "${git_ref}" 2>/dev/null || ! echo >&2 "ERROR: ${BASE_THIS}: could not find git ref for '${git_ref}'" || return 1
+    git cat-file -e "${git_ref}" 2>/dev/null || ! echo >&2 "ERROR: ${base_this}: could not find git ref for '${git_ref}'" || return 1
     #### copy git msg for $git_ref
     if command -v "xsel" >/dev/null 2>&1; then
         git -C "${dir_root}" log "${git_ref}" -1 --pretty=%B | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' | sed '$ {/^$/d}' | tee /dev/stderr | xsel --clipboard
     else
-        echo >&2 "WARNING: ${BASE_THIS}: could not find copy tool xsel, printing msg instead"
+        echo >&2 "WARNING: ${base_this}: could not find copy tool xsel, printing msg instead"
         git -C "${dir_root}" log "${git_ref}" -1 --pretty=%B | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' | sed '$ {/^$/d}'
     fi
 }
