Cleanup with pre-commit

diff --git a/bin/gsrc b/bin/gsrc
--- a/bin/gsrc
+++ b/bin/gsrc
@@ -4,7 +4,7 @@
 
 set -u
 
-PATH_THIS="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)/"$(basename -- "${BASH_SOURCE[0]}")""
+PATH_THIS="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)/$(basename -- "${BASH_SOURCE[0]}")"
 DIR_THIS="$(dirname -- "${PATH_THIS}")"
 BASE_THIS="$(basename -- "${PATH_THIS}")"
 [ -f "${PATH_THIS}" ] && [ -d "${DIR_THIS}" ] && [ -f "${DIR_THIS}/${BASE_THIS}" ] || ! echo >&2 "ERROR: could not generate paths" || exit 1
@@ -48,7 +48,11 @@ _git_source() {
     #### check and clean args
     __check_and_clean_args || return "${?}"
     #### get commit branch started with
-    local base_commit="$(diff -u <(git -C "${dir_root}" rev-list --first-parent "${commit_src}") <(git -C "${dir_root}" rev-list --first-parent "${branch_base}") | sed -ne 's/^ //p' | head -1)"
+    local base_commit=''
+    base_commit="$(diff -u <(git -C "${dir_root}" rev-list --first-parent "${commit_src}") <(git -C "${dir_root}" rev-list --first-parent "${branch_base}") | sed -ne 's/^ //p' | head -1)" || {
+        echo 'ERROR: failed to get base_commit'
+        return 1
+    }
     git cat-file -e "${base_commit}" || ! echo >&2 "ERROR: ${BASE_THIS}: could not find base commit, are you on a branch?" || return 1
     echo "${base_commit}"
 }
